### ISSUE TITLE
Add `Send` version of `Shared` to allowing sharing across threads

### ISSUE THREAD

**Issue by extremeandy** [marieell/shared-stream#2]
Currently `Shared` struct contains `Rc` which is not `Send`.

I think this functionality which be much more useful if it could be shared across threads. This could possible be achieved by adding a variant of `Shared` having `inner: Arc<RwLock<InnerState<S>>>` instead of `inner: Rc<RefCell<InnerState<S>>>`.

**Comment by marieell** [comment]
Thanks, that makes a lot of sense. Is this what you meant?

**Comment by extremeandy** [comment]
Yes, but I think there is a bug in the implementation. Have opened a separate issue: https://github.com/marieell/shared-stream/issues/3

**Comment by extremeandy** [comment]
Also it might be worth making use of `read()` on `RwLock` otherwise there will be a lot of lock contention for the `.write()` lock.

**Comment by marieell** [comment]
> Also it might be worth making use of `read()` on `RwLock` otherwise there will be a lot of lock contention for the `.write()` lock.

I think I'm already using `read()` where possible.

**Comment by extremeandy** [comment]
> > Also it might be worth making use of `read()` on `RwLock` otherwise there will be a lot of lock contention for the `.write()` lock.
> 
> I think I'm already using `read()` where possible.

Which line number(s)? I can only see it being used in `size_hint` and `is_terminated`, but not in `poll_next`.

**Comment by marieell** [comment]
Yes, `poll_next` needs a `mut` `InnerStream`.

**Comment by extremeandy** [comment]
> Yes, `poll_next` needs a `mut` `InnerStream`.

Are you sure? The implementation of `get_item` on `InnerState` currently takes `Pin<&mut Self>`, but this is internal implementation detail. It's possible to use a `read()` lock to inspect the buffer and return a value from `poll_next` before taking a `write()` lock (I tested this locally by making the change myself to the implementation of `poll_next`).

**Comment by marieell** [comment]
You're absolutely right. I implemented that in 62f44b9f26d7e60bfa10df7636d116e4c6cffd92. Edit: On second thought, this clashes heavily with my implementation of #1. I have to think about this.
